name: Ruby gem

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build gem
        run: |
          rake build

      # - name: Publish to RubyGems
      #   run: |
      #     cat << EOF > ~/.gem/credentials
      #     ---
      #     :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
      #     EOF

      #     rake release
